# Site settings
title: York Technical Theatre Society
email: techsoc@yusu.org
description: >
  York Technical Theatre Society
baseurl: "/techsoc-website" # the subpath of your site, e.g. /blog
url: "https://nathanbillis.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-coffeescript
  - jekyll-menus

sass:
  sass_dir: _sass

